POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"second note by this user",
    "important":false,
    "userId":"62285ac7050f824d477ed26b"
}

###
GET http://localhost:3001/api/notes/

###
PUT http://localhost:3001/api/notes/6218a8d46acacdc0075dd2d4
Content-Type: application/json

{
    "content":"HTML is Easy-ish",
    "important":false 
}

